// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import dashboardTabsController from "./dashboard_tabs_controller"
import changePhotoInShow from "./change_photo_in_show"
import expandCard from "./expand_card"

application.register("hello", HelloController)
application.register("dashboard-tabs", dashboardTabsController)
application.register("change-photo-in-show", changePhotoInShow)
application.register("expand-card", expandCard)
